name: Import GPG
description: Import a GPG key to allow for verified commits/tags

branding:
  color: green
  icon: check-circle

inputs:
  gpg_private_key:
    description: GPG private key, base64 encoded. (ASCII ARMOUR)
    required: true
  gpg_passphrase:
    description: Passphrase for the GPG private key
    required: true

runs:
  using: composite
  steps:
    - name: Import GPG Key
      shell: bash
      run: |
        mkdir -p ~/.gnupg
        chmod 700 ~/.gnupg
        
        touch ~/.gnupg/imported-key.key
        printf -- "$GPG_PRIVATE_KEY" > ~/.gnupg/imported-key.key
        # Import the cert reading the passphrase from the STDIN, which will be the password echoed in.
        echo "$GPG_PASSPHRASE" | gpg --pinentry-mode loopback --passphrase-fd 0 --import ~/.gnupg/imported-key.key
      env:
        GPG_PRIVATE_KEY:  ${{ inputs.gpg_private_key }}
        GPG_PASSPHRASE: ${{ inputs.gpg_passphrase }}