name: Configure Java
description: Configure Java JDK

inputs:
  java-version:
    required: false
    description: The version of Java to configure
    default: 17

runs:
  using: composite
  steps:
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        overwrite-settings: false
        cache: maven