name: Create or Update Git Tag
description: Create a new lightweight tag, or update the reference of an existing tag.

inputs:
  tag:
    required: true
    description: "The name of the tag to create/update"
  gpg-key:
    required: true
    description: "The base 64 encoded GPG Key"
  gpg-key-passphrase:
    required: true
    description: "The passphrase of the GPG key"

runs:
  using: composite
  steps:
    - name: Configure GPG Key
      shell: bash
      run: |
        gpg --version
        
        mkdir -p ~/.gnupg
        chmod 700 ~/.gnupg
        
        touch ~/.gnupg/private.key
        printf "$GIT_BOT_GPG_KEY" > ~/.gnupg/private.key
        gpg -d --pinentry-mode loopback --passphrase "$GIT_BOT_GPG_KEY_PASSPHRASE" ~/.gnupg/private.key

      env:
        GIT_BOT_GPG_KEY: ${{ inputs.gpg-key }}
        GIT_BOT_GPG_KEY_PASSPHRASE: ${{ inputs.gpg-key-passphrase }}

