name: Build

on: [ workflow_dispatch ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure GitHub
        uses: ./.github/actions/create-update-tag
        with:
          tag: "anything"
          gpg-key: ${{ secrets.GIT_BOT_GPG_KEY }}
          gpg-key-passphrase: ${{ secrets.GIT_BOT_GPG_KEY_PASSPHRASE }}