name: Build

on: [ workflow_dispatch ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure GitHub
        uses: ./.github/actions/import-gpg
        with:
          gpg_private_key: ${{ secrets.GIT_BOT_GPG_KEY }}
          gpg_passphrase: ${{ secrets.GIT_BOT_GPG_KEY_PASSPHRASE }}
          git_name: ZacheryHarley-GitBot
          git_email: 135477319+ZacheryHarley-GitBot@users.noreply.github.com

      - name: Test Commit
        shell: bash
        run: |
          touch testFile.txt
          
          git add testFile.txt
          git commit -m "Test Commit"
          git push