name: Build

on: [ workflow_dispatch ]

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure Java
        uses: ./.github/actions/configure-java

      - name: Compile Code
        uses: mvn clean compile

      - name: Upload working directory
        uses: ./.github/actions/write-working-dir

  java-tests:
    name: Java Tests
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download working directory
        uses: ./.github/actions/read-working-dir

      - name: Configure Java
        uses: ./.github/actions/configure-java

      - name: Run tests
        run: mvn verify

      - name: JaCoCo Report
        uses: Madrapps/jacoco-report@v1.4
        with:
          paths: ${{ github.workspace }}/lambda-light-test-aggregator/target/site/jacoco-aggregate/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}