name: Code Artifact Cleanup

on: [ workflow_dispatch ]
env:
  AWS_REGION: eu-west-2

jobs:
  remove-unlisted:
    name: Remove Unlisted
    environment: Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_PIPELINE_ROLE }}
          role-session-name: BuildSession
          aws-region: ${{ env.AWS_REGION }}
