name: Code Artifact Cleanup

on: [ workflow_dispatch ]
env:
  AWS_REGION: eu-west-2

jobs:
  remove-unlisted:
    name: Remove Unlisted
    environment: Dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_PIPELINE_ROLE }}
          role-session-name: BuildSession
          aws-region: ${{ env.AWS_REGION }}

      - uses: ./.github/actions/configure-aws
        id: code-artifact
        with:
          domain-owner: ${{ secrets.AWS_REPOSITORY_ACCOUNT }}
          domain: ${{ secrets.DOMAIN }}
          repository: ${{ secrets.AWS_REPOSITORY }}